// flow-typed signature: 5f7e70c8121652a52e546666bbf540c7
// flow-typed version: <<STUB>>/found-relay_v0.2.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'found-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'found-relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'found-relay/lib/index' {
  declare module.exports: any;
}

declare module 'found-relay/lib/RelayRouteRenderer' {
  declare module.exports: any;
}

declare module 'found-relay/lib/Resolver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'found-relay/lib/index.js' {
  declare module.exports: $Exports<'found-relay/lib/index'>;
}
declare module 'found-relay/lib/RelayRouteRenderer.js' {
  declare module.exports: $Exports<'found-relay/lib/RelayRouteRenderer'>;
}
declare module 'found-relay/lib/Resolver.js' {
  declare module.exports: $Exports<'found-relay/lib/Resolver'>;
}
